kind: Pod
apiVersion: v1
metadata:
  name: MyfirstPod
  annotation:
    createdBy: Laherasif
    email: laherasif@gmail.com
  labels:
    type: backend
    env: production
replicas: 4
selector:
  matchLables:
    app: myapp
template:
  metadata:
  labels:
    app: myapp
spec:
  nodeSelector:
   disk_Type: 'ssd'
  containers:
   - name: myfirstpod
    image: laherasif/portfolio
    ports:
    - containerPod: 80  
 
